# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SeatDrawer_pb2 as src_dot_SeatDrawer__pb2


class SeatDrawerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.drawSpecificSeat = channel.unary_unary(
                '/SeatDrawer/drawSpecificSeat',
                request_serializer=src_dot_SeatDrawer__pb2.DrawSeatRequest.SerializeToString,
                response_deserializer=src_dot_SeatDrawer__pb2.DrewResultResponse.FromString,
                )
        self.drawAllSeats = channel.stream_unary(
                '/SeatDrawer/drawAllSeats',
                request_serializer=src_dot_SeatDrawer__pb2.DrawSeatRequest.SerializeToString,
                response_deserializer=src_dot_SeatDrawer__pb2.DrewResultResponse.FromString,
                )


class SeatDrawerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def drawSpecificSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def drawAllSeats(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeatDrawerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'drawSpecificSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.drawSpecificSeat,
                    request_deserializer=src_dot_SeatDrawer__pb2.DrawSeatRequest.FromString,
                    response_serializer=src_dot_SeatDrawer__pb2.DrewResultResponse.SerializeToString,
            ),
            'drawAllSeats': grpc.stream_unary_rpc_method_handler(
                    servicer.drawAllSeats,
                    request_deserializer=src_dot_SeatDrawer__pb2.DrawSeatRequest.FromString,
                    response_serializer=src_dot_SeatDrawer__pb2.DrewResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SeatDrawer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SeatDrawer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def drawSpecificSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SeatDrawer/drawSpecificSeat',
            src_dot_SeatDrawer__pb2.DrawSeatRequest.SerializeToString,
            src_dot_SeatDrawer__pb2.DrewResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def drawAllSeats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SeatDrawer/drawAllSeats',
            src_dot_SeatDrawer__pb2.DrawSeatRequest.SerializeToString,
            src_dot_SeatDrawer__pb2.DrewResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
