# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/SeatDrawer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14src/SeatDrawer.proto\"/\n\x0f\x44rawSeatRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x05\"$\n\x12\x44rewResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x84\x01\n\nSeatDrawer\x12;\n\x10\x64rawSpecificSeat\x12\x10.DrawSeatRequest\x1a\x13.DrewResultResponse\"\x00\x12\x39\n\x0c\x64rawAllSeats\x12\x10.DrawSeatRequest\x1a\x13.DrewResultResponse\"\x00(\x01\x62\x06proto3')



_DRAWSEATREQUEST = DESCRIPTOR.message_types_by_name['DrawSeatRequest']
_DREWRESULTRESPONSE = DESCRIPTOR.message_types_by_name['DrewResultResponse']
DrawSeatRequest = _reflection.GeneratedProtocolMessageType('DrawSeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _DRAWSEATREQUEST,
  '__module__' : 'SeatDrawer_pb2'
  # @@protoc_insertion_point(class_scope:DrawSeatRequest)
  })
_sym_db.RegisterMessage(DrawSeatRequest)

DrewResultResponse = _reflection.GeneratedProtocolMessageType('DrewResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _DREWRESULTRESPONSE,
  '__module__' : 'SeatDrawer_pb2'
  # @@protoc_insertion_point(class_scope:DrewResultResponse)
  })
_sym_db.RegisterMessage(DrewResultResponse)

_SEATDRAWER = DESCRIPTOR.services_by_name['SeatDrawer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRAWSEATREQUEST._serialized_start=24
  _DRAWSEATREQUEST._serialized_end=71
  _DREWRESULTRESPONSE._serialized_start=73
  _DREWRESULTRESPONSE._serialized_end=109
  _SEATDRAWER._serialized_start=112
  _SEATDRAWER._serialized_end=244
# @@protoc_insertion_point(module_scope)
